# Generated by Django 3.1.2 on 2020-11-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('eligibilty', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='upload/products/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
