# Generated by Django 3.1.2 on 2020-11-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_joblist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
    ]
