# Generated by Django 3.1.2 on 2020-11-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_skillcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='skillcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.skillcat'),
            preserve_default=False,
        ),
    ]
